update for templating

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,132 +10,217 @@ env:
     - secure: h6KCoaPtcyTfCeZeCk3cp/avreJai6B/qh5674TO0OesClzpzKjxqfAUThKU2L+Zkjc9qET9n6YXa9iwmaTcZ9xcqr0mDIXMDttsqXU57nOR9mLraZrSARbWKJltLVbC3fYyHlZhs1Z502chgIuMSkIJx1lb5gj4by7cv2tL4BEiyQ0C8XfbxTvw8xiJVS3nmOgMtDe+2PJUmyVpQAXFJHOJhw5aCHLNv9ci478DrijkWKp4QjJ9QHa3vnT3fwccvrQwGbNqM4yZwSGOIKyqUSBVLGbd+fQQgyT3WtF1vvmqRoj48+8E3JL4iTlmPGLlFvIm9e0PI1w9CY+wSlJEN5TEy4U6qrbkiOARhqtK5wwp4MGjDVsLY6FjADStzKtI84eKIHbWkm/AodjjZYC1kFBpzlbq/YMhXEG0EkbNgqqD3yQ1NyCRM+1SnRaaiZ4CwdRsf73yTxxf8F99aJxpxRt7oz2Uhdvit8LKxPG2iGOsLSMYQU75pF1Ipvvz3rDYXHNsAKrYpCm5D+C4LXWutdS9w17kUgYKZ0AbXpSaxA5GC79Oh7obx7Yp9OGjANpJBT8wSH6/xvufSwZhS2BXzu6quvgbndDDb9chPsxOgKW2aePomPtouN7UPR9yAYh5tNCn5rxNKQ3qXWFxw/1OuYGbBv/xxDiE0cXaLuDNsTM=
     - secure: tBZxpaEmIsNl9/5Vb3BlOP5Q6k5aKvYLWhbOdvSw8uITW9nbrsySNPWvf5uzHqrTVTmnL7fS5Sout3TvJWUVmRknrW/JXrlM/LEEZooLK0WzoL48Hk/iQziO0fVBvsLs4RG4OQ4yGjQbjOwU5A/QnA0tzY5NXoJ74EgzF9VORRnRFiJiYsy5xN703CfkiiH/WFJOM9jZxg60JWRdPWsaYC5W/wMFqQTLw8BGZujqE8gwzL7a7h4QaCspHfJQQDNbYoulx1lP+dw5BXwMffTkMRr1ZJEBHwVbvF7zaRypomlTPab3ygH9m3vYQuXHAD85GjFsi5DQL7BSzMUF/dnjVe9gWJ0MVSTGRpkUEZQ+fLv0kBo/hth7hWeF+P0BLhnbiESj+K23JhqtruBCOJ9g81Tss/j/Sgloip16B2bUopUQa5VD7Sp1uLtpfSdBjBb3epJI0Pz/Nx4J+mlsWsQAKwO/gqYdrSnDkuqssF5jZVNgFYSqLjMBWSvLAjAbzCYBvSxIqd4eKi69OoLMOZlBfLepArTwmBflmQhs33nFCMYUW0ZhzYLHMnP70phFvZaaEVwnZew4qhj6wXqcCyvLS8U2I06BTJfu9O0Cwcz49SxVIugIUms3fdeBqQnPqXse4VlEAdgZc2wmtBkdTuZk9quV4IDr8JAtZFUXMAGBL30=
     - secure: PLRDqMVqDu6t5i1sixypiIvmlRyPMnsS1G6CnPC8gYbVRQ4mqpNUdX17UxinQlnxB0crzeSzEwFQ7AUxJDNoGYr0q09olfD7w68yg/qsGfBd5Zke3P1oa19WzaizBAIgsC73wMb0tOa9HhoLV/5WlIENNtChtXtgv1z9Oc9upnpOietvUXD1zbsa82xK5QzNFqQF9aPu7Q3OaZ3e9NtPwoQVPMuRd0O3kj1vFqG2Kb0zbLfUjrrmuZgJzSIif9G8OmnAfRjNBqVItFuMsnA9WnolrPcx7tzySbMR+Mrax/tehO6MLb+P8kriSg9B1vBr5B2r8fDN14HWaQwsSyg58VmpQjdgjo1UJXPzB3jEYLY/lF4BqakIIL4se+Er13AVKWrJTI/IEMr1ztKlFKqMJPk4aLhG9DVLSOgebG7ZcH8ASKSnA6a2zVxog9FgaYZnZkIlO+lUfQpd338piqeK+wz5QaILIt3UVBln6nMB5GoqG8gyV7xUOjJyyRF5tx7tafRXGdCb6sRANiv5PKhYZBLvIscH7ITJt73EZBCrWRI2mqPgx+cjzOlA6OFo1eslGBR2ACLfE/+qAh0koP8JibqK/WWLen0cTAmdIVa2x3rNK1EepEi7Tow4G3fjwzrFvLzLc8DyFXt1Tt9swE6/QjNOb9Y8gC65PLjviDrNw8o=
+    - PROJECT_NAME=derivcheck
+    - GITHUB_REPO_NAME=theochem/derivcheck
+    - CONDA_PKG_NAME_PY=derivcheck
+
+####
+# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
+####
+
 
 # Do not use Travis Python to save some time.
 language: generic
 os:
   - linux
   - osx
-osx_image: xcode6.4
+osx_image: xcode8.3
 dist: trusty
 sudo: false
+
+matrix:
+  # We only test on Linux with one specific Python version, unless we make a release. All
+  # other cases are allowed to fail and will exit early. With the fast_finish option,
+  # travis will send a status update to github as soon as the non-allowed-to-fail has
+  # finished. This speeds up testing in PRs.
+  #
+  # This is not ideal. It would be better to run just one item from the build matrix when
+  # not preparing a release. This is not possible on Travis. There are several tickets on
+  # travis-ci related to this limitation.
+  #
+  #    https://github.com/travis-ci/travis-ci/issues/7451
+  #    https://github.com/travis-ci/travis-ci/issues/7149
+  #    https://github.com/travis-ci/travis-ci/issues/2778
+  #    ...
+  fast_finish: true
+  allow_failures:
+  - os: osx
+
+
+cache:
+  directories:
+    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
+    - $HOME/miniconda # Add the installation to TRAVIS cache.
+
+before_cache:
+- if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
+- rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
+- pip uninstall -y cardboardlint # Cardboardlint always installs even if no changes are made.
 
 branches:
   only:
     - master
     - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/
 
-install:
-# Get miniconda. Take the right version, so re-installing python is only needed for 3.5.
-- if [[ "$MYCONDAPY" == "2.7" ]]; then
-    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
-    else
-      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
-    fi;
+before_install:
+- if ! [[ $TRAVIS_TAG || $TRAVIS_OS_NAME == "linux" && $MYCONDAPY == "2.7" ]]; then exit 0; fi
+# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
+- if test -e $HOME/miniconda/bin; then
+    echo "miniconda already installed.";
   else
-    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
+    echo "Installing miniconda.";
+    rm -rf $HOME/miniconda;
+    mkdir -p $HOME/download;
+    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
+    if [ "${MYCONDAPY}" = "2.7" ]; then
+      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
+        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
+      else
+        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
+      fi;
     else
-      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
+      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
+      else
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
+      fi;
     fi;
+    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
   fi
-- bash miniconda.sh -b -p $HOME/miniconda
+
+
+install:
 - source $HOME/miniconda/bin/activate
 - hash -r
-
 # Configure conda and get a few essentials
 - conda config --set always_yes yes
-# Needed for compiler('c') function, temporary solution:
-# https://github.com/conda/conda-build/issues/2263
-- conda config --add channels c3i_test
-- conda update -q conda
+- conda config --add channels theochem
+- conda install -q conda conda-build
+
+# Set the version info from the git tag
+- git fetch origin --tags &&
+  export PROJECT_VERSION=$(python tools/gitversion.py) &&
+  python tools/gitversion.py python > ${PROJECT_NAME}/version.py;
+
+# Get a list of all build and runtime dependencies.
+# This should become easier, without the copy to conda.recipe.ugly.
+- conda render tools/conda.recipe > tools/conda.recipe/rendered.yaml
+- CONDA_DEPENDENCIES=$(python -c "from yaml import load;
+    req1 = load(open('tools/conda.recipe/rendered.yaml'))['requirements'];
+    deps = req1['build'] + req1['run'];
+    print(' '.join(set(dep.split()[0] for dep in deps)))")
+
 # Get the right python version for building. This only does something for 3.5.
 # Install extra package needed to make things work. Most things can be listed as
 # dependencies on metal.yaml and setup.py, unless setup.py already imports them.
 # Install conda tools for packaging and uploading
-- conda install python=${MYCONDAPY} numpy conda-build anaconda-client
+- conda install -q python=${MYCONDAPY} anaconda-client ${CONDA_DEPENDENCIES}
+# Install more recent stuff with pip
+- pip install --upgrade pylint codecov coverage pycodestyle pydocstyle
+# Show conda info for debugging
 - conda info -a
 
-# Pip has more recent versions of the lint tools than plain conda.
-# Conda-forge broke at some point while writing this, so I'd rather avoid it.
-- pip install pydocstyle pycodestyle pylint codecov coverage
+# Install the latest cardboardlinter
+- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+    pip install --upgrade git+https://github.com/theochem/cardboardlint.git@master#egg=cardboardlint;
+  fi
 
 script:
-# Build the conda package
-- git fetch origin --tags
-- conda build -q tools/conda.recipe
+# Static linting
+# --------------
+- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+    cardboardlinter --refspec $TRAVIS_BRANCH -f static;
+  fi
 
-# Build source package, should work too and needed for deployment to Github and
-# PyPI.
-- python setup.py sdist
+# Unit tests and dynamic linting
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+- if [[ $TRAVIS_TAG ]]; then
+    conda build -q tools/conda.recipe &&
+    conda install --use-local ${CONDA_PKG_NAME_PY} &&
+    (cd; nosetests ${PROJECT_NAME} -v --detailed-errors) &&
+    conda uninstall ${CONDA_PKG_NAME_PY};
+  else
+    python setup.py build_ext -i &&
+    nosetests ${PROJECT_NAME}
+         -v --detailed-errors --with-coverage --cover-package=${PROJECT_NAME}
+         --cover-tests --cover-inclusive --cover-branches &&
+    coverage xml -i &&
 
-# Install Conda package
-- conda install --use-local derivcheck
+    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+       cardboardlinter --refspec $TRAVIS_BRANCH -f 'dynamic';
+    fi
+  fi
 
-# Many options are added to get a thorough coverage analysis.
-- "(cd; nosetests derivcheck -v --processes= --detailed-errors --with-coverage --cover-package=derivcheck --cover-tests --cover-erase --cover-inclusive --cover-branches --cover-xml)"
+# Make CPP and PY source package for github deployment
+- if [[ $TRAVIS_TAG ]]; then
+    python setup.py sdist;
+  fi
 
-# Code quality checks
-- pycodestyle derivcheck/__init__.py derivcheck/basic_example.py setup.py
-- pycodestyle --ignore=E731 derivcheck/test_derivcheck.py
-- pydocstyle setup.py derivcheck
-- pylint derivcheck/__init__.py derivcheck/test_derivcheck.py derivcheck/basic_example.py
+# Some other stuff
+# ----------------
+
+# Compile documentation
+- if [[ -e doc ]]; then
+    (cd doc; make html);
+  fi
 
 after_success:
 # Upload the coverage analysis
-- codecov -f ~/coverage.xml
+- codecov -f coverage.xml
 
-# For deployment, the env var TRAVIS_TAG contains the name of the current tag, if any.
 before_deploy:
-- conda convert --platform all $HOME/miniconda/conda-bld/linux-64/derivcheck-*.tar.bz2 --output-dir conda-bld/
-- cp $HOME/miniconda/conda-bld/linux-64/derivcheck-*.tar.bz2 conda-bld/
+# Try to set some env vars to configure deployment.
+# Please keep the following lines. They will be used again as soon as it is supported on
+# travis. See https://github.com/travis-ci/dpl/issues/613
+#- export IS_PRERELEASE=$(python -c 'import os; tt=os.environ["TRAVIS_TAG"]; print("true" if ("a" in tt or "b" in tt) else "false")')
+#- echo ${IS_PRERELEASE}
+- export ANACONDA_LABEL=$(python -c 'import os; tt=os.environ["TRAVIS_TAG"]; print("alpha" if ("a" in tt) else ("beta" if "b" in tt else "main"))')
+- echo ${ANACONDA_LABEL}
 
+# In deployment, the env var TRAVIS_TAG contains the name of the current version, if any.
 deploy:
 - provider: releases
   skip_cleanup: true
   api_key: ${GITHUB_TOKEN}
-  file: dist/derivcheck-${TRAVIS_TAG}.tar.gz
+  file: dist/${PROJECT_NAME}-${TRAVIS_TAG}.tar.gz
   on:
-    repo: theochem/derivcheck
+    repo: ${GITHUB_REPO_NAME}
     tags: true
-    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
-  prerelease: false
+    condition: "$MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux && $TRAVIS_TAG == *[ab]*"
+  prerelease: true
+
 - provider: releases
   skip_cleanup: true
   api_key: ${GITHUB_TOKEN}
-  file: dist/derivcheck-${TRAVIS_TAG}.tar.gz
+  file: dist/${PROJECT_NAME}-${TRAVIS_TAG}.tar.gz
   on:
-    repo: theochem/derivcheck
+    repo: ${GITHUB_REPO_NAME}
     tags: true
-    condition: "$TRAVIS_TAG == *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
-  prerelease: true
+    condition: "$MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux && $TRAVIS_TAG != *[ab]*"
+  prerelease: false
+
 - provider: script
   skip_cleanup: true
-  script: anaconda -t $ANACONDA_TOKEN upload --force -l alpha conda-bld/**/derivcheck-*.tar.bz2
+  script: anaconda -t $ANACONDA_TOKEN upload --force -l ${ANACONDA_LABEL} ${HOME}/miniconda/conda-bld/*/${PROJECT_NAME}-*.tar.bz2
   on:
-    repo: theochem/derivcheck
+    repo: ${GITHUB_REPO_NAME}
     tags: true
-    condition: "$TRAVIS_TAG == *a* && $TRAVIS_OS_NAME == linux"
-- provider: script
-  skip_cleanup: true
-  script: anaconda -t $ANACONDA_TOKEN upload --force -l beta conda-bld/**/derivcheck-*.tar.bz2
-  on:
-    repo: theochem/derivcheck
-    tags: true
-    condition: "$TRAVIS_TAG == *b* && $TRAVIS_OS_NAME == linux"
-- provider: script
-  skip_cleanup: true
-  script: anaconda -t $ANACONDA_TOKEN upload --force conda-bld/**/derivcheck-*.tar.bz2
-  on:
-    repo: theochem/derivcheck
-    tags: true
-    condition: "$TRAVIS_TAG != *[ab]* && $TRAVIS_OS_NAME == linux"
+
 - provider: pypi
   skip_cleanup: true
   user: theochem
   password: ${PYPI_PASSWD}
   on:
-    repo: theochem/derivcheck
+    repo: ${GITHUB_REPO_NAME}
     tags: true
     condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
+
+- provider: pages
+  skip_cleanup: true
+  github_token: ${GITHUB_TOKEN}
+  project_name: ${PROJECT_NAME}
+  local_dir: doc/_build/html
+  on:
+    repo: ${GITHUB_REPO_NAME}
+    condition: "-e doc && $TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
+    tags: true
