Fixed __version__

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,6 +47,10 @@ script:
 - pycodestyle --ignore=E731 derivcheck/test_derivcheck.py
 - pydocstyle setup.py derivcheck
 - pylint derivcheck/__init__.py derivcheck/test_derivcheck.py derivcheck/basic_example.py
+- if [[ ! -z ${TRAVIS_TAG} && ! -f dist/derivcheck-${TRAVIS_TAG}.tar.gz ]]; then
+  echo "source release dist/derivcheck-${TRAVIS_TAG}.tar.gz not found"
+  exit 1
+  fi
 deploy:
 - provider: releases
   skip_cleanup: true
